import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import "./index.css"

// Register the PWA service worker (generated by vite-plugin-pwa)
import { registerSW } from 'virtual:pwa-register'

const updateSW = registerSW({
  // When a new version is available, reload automatically
  onNeedRefresh() {
    if (confirm('New version available! Reload to update?')) {
      updateSW(true)
    }
  },
  onOfflineReady() {
    console.log('MyStore is ready to work offline!')
  },
})

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App/>
  </StrictMode>,
)
